ENV_NAME: scratchitch 
ENV_KWARGS:
  ctrl_cost_weight: 0
  homogenisation_method: max
  backend: mjx
  disability:
    joint_idx: 13
    joint_restriction_factor: 1e-3
TOTAL_TIMESTEPS: 1e6
NUM_STEPS: 256
NUM_ENVS: 256

NUM_MINIBATCHES: 4
UPDATE_EPOCHS: 4
ANNEAL_LR: False
LR: 1e-3
ENT_COEF: 2e-6
CLIP_EPS: 0.15
RATIO_CLIP_EPS: False
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ADAM_EPS: 1e-8
ACTIVATION: tanh

DISABLE_JIT: False
DEVICE: 0
SEED: 0
NUM_SEEDS: 1

WANDB_MODE: "disabled"

hydra:
  run:
    dir: outputs/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${SEED}
