ENV_NAME: HeuristicEnemySMAX
MAP_NAME: 2s3z
ENV_KWARGS:
  scenario: 2s3z
  see_enemy_actions: True
  walls_cause_death: True
  attack_mode: closest
TOTAL_TIMESTEPS: 1e7
NUM_STEPS: 128
NUM_ENVS: 128
NUM_SEEDS: 1
SEED: 0

# NETWORK ARCHITECTURE
ACTOR_HIDDEN_DIM: 128
CRITIC_HIDDEN_DIM: 128
ACTIVATION: relu

# RL HYPERPARAMETERS
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
ANNEAL_LR: False
LR: 2.5e-4
ENT_COEF: 1e-4
CLIP_EPS: 0.2
SCALE_CLIP_EPS: False
RATIO_CLIP_EPS: False
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ADAM_EPS: 1e-8

# COMPUTE OPTIONS
ADVANTAGE_UNROLL_DEPTH: 8
DISABLE_JIT: False
DEVICE: 0

# SWEEPER SETTINGS
SWEEP:
  num_configs: 4
  lr:
    min: -4.0
    max: -3.0
  ent_coef: false
  clip_eps: false

hydra:
  job:
    chdir: true
  run:
    dir: outputs/smax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/smax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${RATIO_CLIP_EPS}
